version: '3'

services:
  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    volumes:
      - ./laravel:/var/www/html
    networks:
      - backend
      - frontend

  wordpress:
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - backend

  nginx:
    build:
      context: ./services/nginx
      args:
        - CHANGE_SOURCE=${CHANGE_SOURCE}
      dockerfile: Dockerfile    
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
      - "${VARNISH_BACKEND_PORT}:81"
    volumes:
      # - ./services/nginx/conf.d:/etc/nginx/conf.d
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
    networks:
      - backend

  # phpunit:
  #   image: binarydata/phpunit
  #   depends_on:
  #   #  - mysql
  #    - redis
  #   links:
  #    - database:database
  #    - redis:redis
  #   volumes_from:
  #    - data

  mysql:
    image: "mysql:${MYSQL_VERSION}"
    env_file: "${MYSQL_ENV_FILE}"
    ports:
      - "3306:3306"
    volumes:
      - ./machine/mysql/databases:/var/lib/mysql
      - ./machine/mysql/cnf:/etc/mysql/conf.d
  cache:
    image: memcached
    ports:
      - "11211:11211"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

networks:
  backend:
  frontend: